Update the blob storage adapter.
opendatadiscovery/odd-collector-azure pull request #18
Opened 2023-07-24 15:14 UTC by ykobuk

2023-07-27 11:30 UTC, Vixtir requested changes

2023-07-27 11:30 UTC, Vixtir commented on odd_collector_azure/adapters/blob_storage/mapper/container.py
>      container, *keys = folder.path.split("/")
Same as above

2023-08-04 13:57 UTC, ykobuk commented on odd_collector_azure/adapters/blob_storage/adapter.py
>      def get_data_source_oddrn(self) -> str:
Done.

2023-08-04 13:57 UTC, ykobuk commented on odd_collector_azure/adapters/blob_storage/mapper/container.py
>      container, *keys = file.path.split("/")
Done.

2023-08-04 13:58 UTC, ykobuk commented on odd_collector_azure/adapters/blob_storage/mapper/container.py
>      container, *keys = folder.path.split("/")
Done.

2023-08-14 07:49 UTC, Vixtir approved these changes

2023-08-14 07:49 UTC, merged